// <auto-generated />
using System;
using CentralKitchenAndFranchise.DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CentralKitchenAndFranchise.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331020750_AddInventoryLedgerFoundation")]
    partial class AddInventoryLedgerFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Allocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllocationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DemandAggregationId")
                        .HasColumnType("integer");

                    b.HasKey("AllocationId");

                    b.HasIndex("DemandAggregationId");

                    b.ToTable("allocations", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.AllocationItem", b =>
                {
                    b.Property<int>("AllocationItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllocationItemId"));

                    b.Property<int>("AllocationId")
                        .HasColumnType("integer");

                    b.Property<int?>("CentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("AllocationItemId");

                    b.HasIndex("AllocationId");

                    b.HasIndex("CentralKitchenId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("ProductId");

                    b.ToTable("allocation_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityName")
                        .HasColumnType("text");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<string>("NewDataJson")
                        .HasColumnType("text");

                    b.Property<string>("OldDataJson")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AuditLogId");

                    b.HasIndex("CentralKitchenId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Bom", b =>
                {
                    b.Property<int>("BomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BomId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("BomId");

                    b.HasIndex("ProductId");

                    b.ToTable("boms", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.BomItem", b =>
                {
                    b.Property<int>("BomItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BomItemId"));

                    b.Property<int>("BomId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("BomItemId");

                    b.HasIndex("BomId");

                    b.HasIndex("IngredientId");

                    b.ToTable("bom_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.CentralKitchen", b =>
                {
                    b.Property<int>("CentralKitchenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CentralKitchenId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CentralKitchenId");

                    b.ToTable("central_kitchens", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryIngredientItem", b =>
                {
                    b.Property<int>("DeliveryIngredientItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryIngredientItemId"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<string>("DropReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDropped")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("DeliveryIngredientItemId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("IngredientId");

                    b.ToTable("delivery_ingredient_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryPlan", b =>
                {
                    b.Property<int>("DeliveryPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryPlanId"));

                    b.Property<int?>("CentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<int?>("StoreOrderId")
                        .HasColumnType("integer");

                    b.HasKey("DeliveryPlanId");

                    b.HasIndex("CentralKitchenId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("StoreOrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_delivery_plans_store_order_id")
                        .HasFilter("\"StoreOrderId\" IS NOT NULL");

                    b.ToTable("delivery_plans", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryProductItem", b =>
                {
                    b.Property<int>("DeliveryProductItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryProductItemId"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<string>("DropReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDropped")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("DeliveryProductItemId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("ProductId");

                    b.ToTable("delivery_product_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DemandAggregation", b =>
                {
                    b.Property<int>("DemandAggregationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DemandAggregationId"));

                    b.Property<int>("CentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PlanDate")
                        .HasColumnType("date");

                    b.HasKey("DemandAggregationId");

                    b.HasIndex("CentralKitchenId", "PlanDate")
                        .IsUnique();

                    b.ToTable("demand_aggregations", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DemandItem", b =>
                {
                    b.Property<int>("DemandItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DemandItemId"));

                    b.Property<int>("DemandAggregationId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("DemandItemId");

                    b.HasIndex("DemandAggregationId");

                    b.HasIndex("ProductId");

                    b.ToTable("demand_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Franchise", b =>
                {
                    b.Property<int>("FranchiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FranchiseId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("CentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FranchiseId");

                    b.HasIndex("CentralKitchenId");

                    b.ToTable("franchises", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SafetyStock")
                        .HasColumnType("numeric");

                    b.Property<int>("ShelfLifeDays")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WasteThreshold")
                        .HasColumnType("numeric");

                    b.HasKey("IngredientId");

                    b.HasIndex("SupplierId");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.InventoryLedgerEntry", b =>
                {
                    b.Property<long>("InventoryLedgerEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InventoryLedgerEntryId"));

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ActualQuantitySnapshot")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BatchCodeSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("BatchCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BatchId")
                        .HasColumnType("integer");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CounterpartyBatchId")
                        .HasColumnType("integer");

                    b.Property<int?>("CounterpartyScopeId")
                        .HasColumnType("integer");

                    b.Property<string>("CounterpartyScopeType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<int?>("DeliveryPlanId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DeltaQuantity")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("DropReasonSnapshot")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("DroppedQuantitySnapshot")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("ExpiredAtSnapshot")
                        .HasColumnType("date");

                    b.Property<bool>("IsNonStockEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("RequestedQuantitySnapshot")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ScopeId")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.Property<string>("StockBucket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("StoreOrderId")
                        .HasColumnType("integer");

                    b.HasKey("InventoryLedgerEntryId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("DeliveryPlanId");

                    b.HasIndex("StoreOrderId");

                    b.HasIndex("CorrelationId", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("UX_inventory_ledger_entries_correlation_sequence");

                    b.HasIndex("BatchId", "OccurredAtUtc", "InventoryLedgerEntryId")
                        .HasDatabaseName("IX_inventory_ledger_entries_batch_occurred_id")
                        .HasFilter("\"BatchId\" IS NOT NULL");

                    b.HasIndex("DeliveryId", "OccurredAtUtc", "InventoryLedgerEntryId")
                        .HasDatabaseName("IX_inventory_ledger_entries_delivery_occurred_id")
                        .HasFilter("\"DeliveryId\" IS NOT NULL");

                    b.HasIndex("ItemType", "ItemId", "OccurredAtUtc", "InventoryLedgerEntryId")
                        .HasDatabaseName("IX_inventory_ledger_entries_item_occurred_id");

                    b.HasIndex("ScopeType", "ScopeId", "OccurredAtUtc", "InventoryLedgerEntryId")
                        .HasDatabaseName("IX_inventory_ledger_entries_scope_occurred_id");

                    b.ToTable("inventory_ledger_entries", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.InventoryMovement", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovementId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MovementId");

                    b.HasIndex("BatchId");

                    b.ToTable("inventory_movements", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PermissionId");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShelfLifeDays")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BatchId"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInTransit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductionRunId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("BatchId");

                    b.HasIndex("CentralKitchenId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("ProductionRunId");

                    b.HasIndex("ProductId", "CentralKitchenId", "BatchCode")
                        .IsUnique()
                        .HasDatabaseName("UX_product_batches_product_ck_batchcode")
                        .HasFilter("\"CentralKitchenId\" IS NOT NULL AND \"FranchiseId\" IS NULL AND \"DeliveryId\" IS NULL");

                    b.HasIndex("ProductId", "FranchiseId", "BatchCode")
                        .IsUnique()
                        .HasDatabaseName("UX_product_batches_product_franchise_batchcode")
                        .HasFilter("\"FranchiseId\" IS NOT NULL AND \"CentralKitchenId\" IS NULL AND \"DeliveryId\" IS NULL");

                    b.ToTable("product_batches", null, t =>
                        {
                            t.HasCheckConstraint("CK_product_batches_onhand_no_delivery", "\"IsInTransit\" = true OR \"DeliveryId\" IS NULL");

                            t.HasCheckConstraint("CK_product_batches_owner", "\r\n                        (\r\n                            \"FranchiseId\" IS NOT NULL\r\n                            AND \"CentralKitchenId\" IS NULL\r\n                        )\r\n                        OR\r\n                        (\r\n                            \"FranchiseId\" IS NULL\r\n                            AND \"CentralKitchenId\" IS NOT NULL\r\n                        )");

                            t.HasCheckConstraint("CK_product_batches_transit_has_delivery", "\"IsInTransit\" = false OR \"DeliveryId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductMovement", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovementId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MovementId");

                    b.HasIndex("BatchId");

                    b.ToTable("product_movements", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", b =>
                {
                    b.Property<int>("ProductionPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductionPlanId"));

                    b.Property<int>("CentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PlanDate")
                        .HasColumnType("date");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductionPlanId");

                    b.HasIndex("CentralKitchenId");

                    b.ToTable("production_plans", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlanItem", b =>
                {
                    b.Property<int>("ProductionPlanItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductionPlanItemId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionPlanId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("ProductionPlanItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionPlanId");

                    b.ToTable("production_plan_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionRun", b =>
                {
                    b.Property<int>("ProductionRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductionRunId"));

                    b.Property<int>("CentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ProductionDate")
                        .HasColumnType("date");

                    b.Property<int>("ProductionPlanId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RunCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("ProductionRunId");

                    b.HasIndex("CentralKitchenId");

                    b.HasIndex("ProductionPlanId");

                    b.ToTable("production_runs", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ReceivingReport", b =>
                {
                    b.Property<int>("ReceivingReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReceivingReportId"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReceivedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("ReceivingReportId");

                    b.HasIndex("DeliveryId")
                        .IsUnique();

                    b.ToTable("receiving_reports", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId");

                    b.HasIndex("ProductId");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.RevokedToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("revoked_tokens", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SalesRecord", b =>
                {
                    b.Property<int>("SalesRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalesRecordId"));

                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("SoldAt")
                        .HasColumnType("date");

                    b.HasKey("SalesRecordId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("ProductId");

                    b.ToTable("sales_records", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreCatalog", b =>
                {
                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FranchiseId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("store_catalog", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", b =>
                {
                    b.Property<int>("StoreOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreOrderId"));

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryStatusNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeliveryStatusUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeliveryStatusUpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ForwardNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ForwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ForwardedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("PreparedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PreparedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("PreparingNote")
                        .HasColumnType("text");

                    b.Property<string>("ProcessingNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessingNoteUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProcessingNoteUpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiveNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReceivedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StoreNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StoreOrderId");

                    b.HasIndex("Status");

                    b.HasIndex("FranchiseId", "OrderDate");

                    b.ToTable("store_orders", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrderHistory", b =>
                {
                    b.Property<int>("StoreOrderHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreOrderHistoryId"));

                    b.Property<string>("ActionLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("StoreOrderId")
                        .HasColumnType("integer");

                    b.HasKey("StoreOrderHistoryId");

                    b.HasIndex("StoreOrderId");

                    b.ToTable("store_order_histories", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrderIngredientItem", b =>
                {
                    b.Property<int>("StoreOrderIngredientItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreOrderIngredientItemId"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StoreOrderId")
                        .HasColumnType("integer");

                    b.HasKey("StoreOrderIngredientItemId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("StoreOrderId");

                    b.ToTable("store_order_ingredient_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrderItem", b =>
                {
                    b.Property<int>("StoreOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreOrderItemId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("StoreOrderId")
                        .HasColumnType("integer");

                    b.HasKey("StoreOrderItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreOrderId");

                    b.ToTable("store_order_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("ContactInfo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SupplierId");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SupportRequest", b =>
                {
                    b.Property<int>("SupportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupportRequestId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SupportRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("support_requests", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SystemSetting", b =>
                {
                    b.Property<int>("SystemSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SystemSettingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SystemSettingId");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.UserWorkAssignment", b =>
                {
                    b.Property<int>("UserWorkAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserWorkAssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserWorkAssignmentId");

                    b.HasIndex("CentralKitchenId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("UserId");

                    b.ToTable("user_work_assignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_work_assignments_owner", "\r\n                (\r\n                    (\"AssignmentType\" = 'FRANCHISE' AND \"FranchiseId\" IS NOT NULL AND \"CentralKitchenId\" IS NULL)\r\n                    OR\r\n                    (\"AssignmentType\" = 'CENTRAL_KITCHEN' AND \"FranchiseId\" IS NULL AND \"CentralKitchenId\" IS NOT NULL)\r\n                )");
                        });
                });

            modelBuilder.Entity("Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryId"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("FromCentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsStockCommitted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeliveryId");

                    b.HasIndex("DeliveryPlanId");

                    b.HasIndex("FromCentralKitchenId");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("IngredientBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BatchId"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CentralKitchenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInTransit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("BatchId");

                    b.HasIndex("CentralKitchenId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("IngredientId", "CentralKitchenId", "BatchCode")
                        .IsUnique()
                        .HasDatabaseName("UX_ingredient_batches_ingredient_ck_batchcode")
                        .HasFilter("\"CentralKitchenId\" IS NOT NULL AND \"FranchiseId\" IS NULL AND \"DeliveryId\" IS NULL");

                    b.HasIndex("IngredientId", "FranchiseId", "BatchCode")
                        .IsUnique()
                        .HasDatabaseName("UX_ingredient_batches_ingredient_franchise_batchcode")
                        .HasFilter("\"FranchiseId\" IS NOT NULL AND \"CentralKitchenId\" IS NULL AND \"DeliveryId\" IS NULL");

                    b.ToTable("ingredient_batches", null, t =>
                        {
                            t.HasCheckConstraint("CK_ingredient_batches_onhand_no_delivery", "\"IsInTransit\" = true OR \"DeliveryId\" IS NULL");

                            t.HasCheckConstraint("CK_ingredient_batches_transit_has_delivery", "\"IsInTransit\" = false OR \"DeliveryId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_ingredient_batches_type_owner", "\r\n                        (\r\n                            \"Type\" = 'FRANCHISE'\r\n                            AND \"FranchiseId\" IS NOT NULL\r\n                            AND \"CentralKitchenId\" IS NULL\r\n                        )\r\n                        OR\r\n                        (\r\n                            \"Type\" = 'CENTRAL_KITCHEN'\r\n                            AND \"FranchiseId\" IS NULL\r\n                            AND \"CentralKitchenId\" IS NOT NULL\r\n                        )");
                        });
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Allocation", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.DemandAggregation", "DemandAggregation")
                        .WithMany("Allocations")
                        .HasForeignKey("DemandAggregationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandAggregation");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.AllocationItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Allocation", "Allocation")
                        .WithMany("AllocationItems")
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.CentralKitchen", "CentralKitchen")
                        .WithMany("AllocationItems")
                        .HasForeignKey("CentralKitchenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("AllocationItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Allocation");

                    b.Navigation("CentralKitchen");

                    b.Navigation("Franchise");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.AuditLog", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.CentralKitchen", "CentralKitchen")
                        .WithMany()
                        .HasForeignKey("CentralKitchenId");

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId");

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CentralKitchen");

                    b.Navigation("Franchise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Bom", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", null)
                        .WithMany("Boms")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.BomItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Bom", "Bom")
                        .WithMany("Items")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Ingredient", "Ingredient")
                        .WithMany("BomItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bom");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryIngredientItem", b =>
                {
                    b.HasOne("Delivery", "Delivery")
                        .WithMany("IngredientItems")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Ingredient", "Ingredient")
                        .WithMany("DeliveryIngredientItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryPlan", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.CentralKitchen", "CentralKitchen")
                        .WithMany("DeliveryPlans")
                        .HasForeignKey("CentralKitchenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", "StoreOrder")
                        .WithMany()
                        .HasForeignKey("StoreOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CentralKitchen");

                    b.Navigation("Franchise");

                    b.Navigation("StoreOrder");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryProductItem", b =>
                {
                    b.HasOne("Delivery", "Delivery")
                        .WithMany("ProductItems")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("DeliveryProductItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DemandAggregation", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.CentralKitchen", "CentralKitchen")
                        .WithMany()
                        .HasForeignKey("CentralKitchenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentralKitchen");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DemandItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.DemandAggregation", "DemandAggregation")
                        .WithMany("DemandItems")
                        .HasForeignKey("DemandAggregationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("DemandItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandAggregation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Franchise", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.CentralKitchen", "CentralKitchen")
                        .WithMany("Franchises")
                        .HasForeignKey("CentralKitchenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentralKitchen");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Ingredient", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Supplier", "Supplier")
                        .WithMany("Ingredients")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.InventoryLedgerEntry", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Delivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.DeliveryPlan", null)
                        .WithMany()
                        .HasForeignKey("DeliveryPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", null)
                        .WithMany()
                        .HasForeignKey("StoreOrderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.InventoryMovement", b =>
                {
                    b.HasOne("IngredientBatch", "Batch")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductBatch", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.CentralKitchen", "CentralKitchen")
                        .WithMany("ProductBatches")
                        .HasForeignKey("CentralKitchenId");

                    b.HasOne("Delivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId");

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("ProductBatches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.ProductionRun", "ProductionRun")
                        .WithMany("ProductBatches")
                        .HasForeignKey("ProductionRunId");

                    b.Navigation("CentralKitchen");

                    b.Navigation("Franchise");

                    b.Navigation("Product");

                    b.Navigation("ProductionRun");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductMovement", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.ProductBatch", "Batch")
                        .WithMany("ProductMovements")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.CentralKitchen", "CentralKitchen")
                        .WithMany("ProductionPlans")
                        .HasForeignKey("CentralKitchenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentralKitchen");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlanItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("ProductionPlanItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", "ProductionPlan")
                        .WithMany("Items")
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionRun", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.CentralKitchen", "CentralKitchen")
                        .WithMany("ProductionRuns")
                        .HasForeignKey("CentralKitchenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", "ProductionPlan")
                        .WithMany("ProductionRuns")
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentralKitchen");

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ReceivingReport", b =>
                {
                    b.HasOne("Delivery", "Delivery")
                        .WithMany("ReceivingReports")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Recipe", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", null)
                        .WithMany("Recipes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.RolePermission", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SalesRecord", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("SalesRecords")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("SalesRecords")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreCatalog", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("StoreCatalogs")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("StoreCatalogs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("StoreOrders")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrderHistory", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", "StoreOrder")
                        .WithMany("Histories")
                        .HasForeignKey("StoreOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreOrder");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrderIngredientItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Ingredient", "Ingredient")
                        .WithMany("StoreOrderIngredientItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", "StoreOrder")
                        .WithMany("IngredientItems")
                        .HasForeignKey("StoreOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("StoreOrder");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrderItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("StoreOrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", "StoreOrder")
                        .WithMany("Items")
                        .HasForeignKey("StoreOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StoreOrder");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SupportRequest", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.User", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.UserWorkAssignment", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.CentralKitchen", "CentralKitchen")
                        .WithMany("WorkAssignments")
                        .HasForeignKey("CentralKitchenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("WorkAssignments")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.User", "User")
                        .WithMany("WorkAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentralKitchen");

                    b.Navigation("Franchise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Delivery", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.DeliveryPlan", "DeliveryPlan")
                        .WithMany("Deliveries")
                        .HasForeignKey("DeliveryPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.CentralKitchen", "FromCentralKitchen")
                        .WithMany()
                        .HasForeignKey("FromCentralKitchenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeliveryPlan");

                    b.Navigation("FromCentralKitchen");
                });

            modelBuilder.Entity("IngredientBatch", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.CentralKitchen", "CentralKitchen")
                        .WithMany("IngredientBatches")
                        .HasForeignKey("CentralKitchenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Delivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("IngredientBatches")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Ingredient", "Ingredient")
                        .WithMany("IngredientBatches")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentralKitchen");

                    b.Navigation("Franchise");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Allocation", b =>
                {
                    b.Navigation("AllocationItems");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Bom", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.CentralKitchen", b =>
                {
                    b.Navigation("AllocationItems");

                    b.Navigation("DeliveryPlans");

                    b.Navigation("Franchises");

                    b.Navigation("IngredientBatches");

                    b.Navigation("ProductBatches");

                    b.Navigation("ProductionPlans");

                    b.Navigation("ProductionRuns");

                    b.Navigation("WorkAssignments");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryPlan", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DemandAggregation", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("DemandItems");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Franchise", b =>
                {
                    b.Navigation("IngredientBatches");

                    b.Navigation("SalesRecords");

                    b.Navigation("StoreCatalogs");

                    b.Navigation("StoreOrders");

                    b.Navigation("WorkAssignments");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Ingredient", b =>
                {
                    b.Navigation("BomItems");

                    b.Navigation("DeliveryIngredientItems");

                    b.Navigation("IngredientBatches");

                    b.Navigation("StoreOrderIngredientItems");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Product", b =>
                {
                    b.Navigation("AllocationItems");

                    b.Navigation("Boms");

                    b.Navigation("DeliveryProductItems");

                    b.Navigation("DemandItems");

                    b.Navigation("ProductBatches");

                    b.Navigation("ProductionPlanItems");

                    b.Navigation("Recipes");

                    b.Navigation("SalesRecords");

                    b.Navigation("StoreCatalogs");

                    b.Navigation("StoreOrderItems");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductBatch", b =>
                {
                    b.Navigation("ProductMovements");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ProductionRuns");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionRun", b =>
                {
                    b.Navigation("ProductBatches");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("IngredientItems");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Supplier", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.User", b =>
                {
                    b.Navigation("WorkAssignments");
                });

            modelBuilder.Entity("Delivery", b =>
                {
                    b.Navigation("IngredientItems");

                    b.Navigation("ProductItems");

                    b.Navigation("ReceivingReports");
                });

            modelBuilder.Entity("IngredientBatch", b =>
                {
                    b.Navigation("InventoryMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
