// <auto-generated />
using System;
using CentralKitchenAndFranchise.DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CentralKitchenAndFranchise.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213090314_Week5_Task18_RbacHardening")]
    partial class Week5_Task18_RbacHardening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Allocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllocationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DemandAggregationId")
                        .HasColumnType("integer");

                    b.HasKey("AllocationId");

                    b.HasIndex("DemandAggregationId");

                    b.ToTable("allocations", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.AllocationItem", b =>
                {
                    b.Property<int>("AllocationItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllocationItemId"));

                    b.Property<int>("AllocationId")
                        .HasColumnType("integer");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("AllocationItemId");

                    b.HasIndex("AllocationId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("ProductId");

                    b.ToTable("allocation_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityName")
                        .HasColumnType("text");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<string>("NewDataJson")
                        .HasColumnType("text");

                    b.Property<string>("OldDataJson")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AuditLogId");

                    b.HasIndex("Action");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Bom", b =>
                {
                    b.Property<int>("BomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BomId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("BomId");

                    b.HasIndex("ProductId", "Version")
                        .IsUnique();

                    b.ToTable("boms", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.BomItem", b =>
                {
                    b.Property<int>("BomItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BomItemId"));

                    b.Property<int>("BomId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("BomItemId");

                    b.HasIndex("BomId");

                    b.HasIndex("IngredientId");

                    b.ToTable("bom_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryId"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DeliveredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DeliveryPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("FromFranchiseId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("CREATED");

                    b.HasKey("DeliveryId");

                    b.HasIndex("DeliveryPlanId");

                    b.HasIndex("FromFranchiseId");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryIngredientItem", b =>
                {
                    b.Property<int>("DeliveryIngredientItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryIngredientItemId"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("DeliveryIngredientItemId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("DeliveryId", "IngredientId")
                        .IsUnique();

                    b.ToTable("delivery_ingredient_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryPlan", b =>
                {
                    b.Property<int>("DeliveryPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryPlanId"));

                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date");

                    b.HasKey("DeliveryPlanId");

                    b.HasIndex("FranchiseId");

                    b.ToTable("delivery_plans", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryProductItem", b =>
                {
                    b.Property<int>("DeliveryProductItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryProductItemId"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("DeliveryProductItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("DeliveryId", "ProductId")
                        .IsUnique();

                    b.ToTable("delivery_product_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DemandAggregation", b =>
                {
                    b.Property<int>("DemandAggregationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DemandAggregationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("PlanDate")
                        .HasColumnType("date");

                    b.HasKey("DemandAggregationId");

                    b.ToTable("demand_aggregations", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DemandItem", b =>
                {
                    b.Property<int>("DemandItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DemandItemId"));

                    b.Property<int>("DemandAggregationId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("DemandItemId");

                    b.HasIndex("DemandAggregationId");

                    b.HasIndex("ProductId");

                    b.ToTable("demand_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Franchise", b =>
                {
                    b.Property<int>("FranchiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FranchiseId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FranchiseId");

                    b.ToTable("franchises", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("SafetyStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("WasteThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.HasKey("IngredientId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.IngredientBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BatchId"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ExpiredAt")
                        .HasColumnType("date");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("BatchId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("IngredientId", "BatchCode", "FranchiseId")
                        .IsUnique();

                    b.ToTable("ingredient_batches", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.InventoryMovement", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovementId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MovementId");

                    b.HasIndex("BatchId");

                    b.HasIndex("DeliveryId");

                    b.ToTable("inventory_movements", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PermissionId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("FINISHED");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BatchId"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("ExpiredAt")
                        .HasColumnType("date");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("BatchId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("ProductId", "BatchCode", "FranchiseId")
                        .IsUnique();

                    b.ToTable("product_batches", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductMovement", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovementId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MovementId");

                    b.HasIndex("BatchId");

                    b.HasIndex("DeliveryId");

                    b.ToTable("product_movements", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionBatch", b =>
                {
                    b.Property<int>("ProductionBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductionBatchId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ProductionPlanId")
                        .HasColumnType("integer");

                    b.HasKey("ProductionBatchId");

                    b.HasIndex("ProductionPlanId");

                    b.ToTable("production_batches", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", b =>
                {
                    b.Property<int>("ProductionPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductionPlanId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PlanDate")
                        .HasColumnType("date");

                    b.HasKey("ProductionPlanId");

                    b.HasIndex("FranchiseId");

                    b.ToTable("production_plans", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlanItem", b =>
                {
                    b.Property<int>("ProductionPlanItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductionPlanItemId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionPlanId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("ProductionPlanItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionPlanId");

                    b.ToTable("production_plan_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ReceivingReport", b =>
                {
                    b.Property<int>("ReceivingReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReceivingReportId"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ReceivingReportId");

                    b.HasIndex("DeliveryId");

                    b.ToTable("receiving_reports", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId");

                    b.HasIndex("ProductId", "Version")
                        .IsUnique();

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.RevokedToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.ToTable("revoked_tokens", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SalesRecord", b =>
                {
                    b.Property<int>("SalesRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalesRecordId"));

                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("SoldAt")
                        .HasColumnType("date");

                    b.HasKey("SalesRecordId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("ProductId");

                    b.ToTable("sales_records", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreCatalog", b =>
                {
                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ACTIVE");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("FranchiseId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("store_catalog", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", b =>
                {
                    b.Property<int>("StoreOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreOrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StoreOrderId");

                    b.HasIndex("FranchiseId");

                    b.ToTable("store_orders", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrderItem", b =>
                {
                    b.Property<int>("StoreOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreOrderItemId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("StoreOrderId")
                        .HasColumnType("integer");

                    b.HasKey("StoreOrderItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreOrderId");

                    b.ToTable("store_order_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("ContactInfo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SupplierId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SupportRequest", b =>
                {
                    b.Property<int>("SupportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupportRequestId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SupportRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("support_requests", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SystemSetting", b =>
                {
                    b.Property<int>("SystemSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SystemSettingId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("SystemSettingId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.UserFranchise", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "FranchiseId");

                    b.HasIndex("FranchiseId");

                    b.ToTable("user_franchises", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Allocation", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.DemandAggregation", "DemandAggregation")
                        .WithMany()
                        .HasForeignKey("DemandAggregationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandAggregation");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.AllocationItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Allocation", "Allocation")
                        .WithMany("AllocationItems")
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("AllocationItems")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("AllocationItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allocation");

                    b.Navigation("Franchise");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.AuditLog", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId");

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Franchise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Bom", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("Boms")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.BomItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Bom", "Bom")
                        .WithMany("Items")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Ingredient", "Ingredient")
                        .WithMany("BomItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bom");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Delivery", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.DeliveryPlan", "DeliveryPlan")
                        .WithMany("Deliveries")
                        .HasForeignKey("DeliveryPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "FromFranchise")
                        .WithMany()
                        .HasForeignKey("FromFranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryPlan");

                    b.Navigation("FromFranchise");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryIngredientItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Delivery", "Delivery")
                        .WithMany("IngredientItems")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryPlan", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("DeliveryPlans")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryProductItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Delivery", "Delivery")
                        .WithMany("ProductItems")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("DeliveryProductItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DemandItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.DemandAggregation", "DemandAggregation")
                        .WithMany("DemandItems")
                        .HasForeignKey("DemandAggregationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("DemandItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandAggregation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.IngredientBatch", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("IngredientBatches")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Ingredient", "Ingredient")
                        .WithMany("IngredientBatches")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.InventoryMovement", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.IngredientBatch", "Batch")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductBatch", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("ProductBatches")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("ProductBatches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductMovement", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.ProductBatch", "Batch")
                        .WithMany("ProductMovements")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionBatch", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", "ProductionPlan")
                        .WithMany("ProductionBatches")
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("ProductionPlans")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlanItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("ProductionPlanItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", "ProductionPlan")
                        .WithMany("Items")
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ReceivingReport", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Delivery", "Delivery")
                        .WithMany("ReceivingReports")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Recipe", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("Recipes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.RolePermission", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SalesRecord", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("SalesRecords")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("SalesRecords")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreCatalog", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("StoreCatalogs")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("StoreCatalogs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("StoreOrders")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrderItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany("StoreOrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", "StoreOrder")
                        .WithMany("Items")
                        .HasForeignKey("StoreOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StoreOrder");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SupportRequest", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.User", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.UserFranchise", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany("UserFranchises")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.User", "User")
                        .WithMany("UserFranchises")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Allocation", b =>
                {
                    b.Navigation("AllocationItems");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Bom", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Delivery", b =>
                {
                    b.Navigation("IngredientItems");

                    b.Navigation("ProductItems");

                    b.Navigation("ReceivingReports");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryPlan", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DemandAggregation", b =>
                {
                    b.Navigation("DemandItems");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Franchise", b =>
                {
                    b.Navigation("AllocationItems");

                    b.Navigation("DeliveryPlans");

                    b.Navigation("IngredientBatches");

                    b.Navigation("ProductBatches");

                    b.Navigation("ProductionPlans");

                    b.Navigation("SalesRecords");

                    b.Navigation("StoreCatalogs");

                    b.Navigation("StoreOrders");

                    b.Navigation("UserFranchises");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Ingredient", b =>
                {
                    b.Navigation("BomItems");

                    b.Navigation("IngredientBatches");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.IngredientBatch", b =>
                {
                    b.Navigation("InventoryMovements");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Product", b =>
                {
                    b.Navigation("AllocationItems");

                    b.Navigation("Boms");

                    b.Navigation("DeliveryProductItems");

                    b.Navigation("DemandItems");

                    b.Navigation("ProductBatches");

                    b.Navigation("ProductionPlanItems");

                    b.Navigation("Recipes");

                    b.Navigation("SalesRecords");

                    b.Navigation("StoreCatalogs");

                    b.Navigation("StoreOrderItems");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductBatch", b =>
                {
                    b.Navigation("ProductMovements");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ProductionBatches");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.User", b =>
                {
                    b.Navigation("UserFranchises");
                });
#pragma warning restore 612, 618
        }
    }
}
