// <auto-generated />
using System;
using CentralKitchenAndFranchise.DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CentralKitchenAndFranchise.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128135531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Allocation", b =>
                {
                    b.Property<Guid>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_id");

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("ApproverUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DemandAggregationId")
                        .HasColumnType("uuid")
                        .HasColumnName("demand_aggregation_id");

                    b.HasKey("AllocationId");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("DemandAggregationId");

                    b.ToTable("allocations", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.AllocationItem", b =>
                {
                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_id");

                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uuid")
                        .HasColumnName("franchise_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("AllocatedQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("allocated_quantity");

                    b.HasKey("AllocationId", "FranchiseId", "ProductId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("ProductId");

                    b.ToTable("allocation_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_log_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ActorId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Bom", b =>
                {
                    b.Property<Guid>("BomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("bom_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("BomId");

                    b.HasIndex("ProductId");

                    b.ToTable("boms", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.BomItem", b =>
                {
                    b.Property<Guid>("BomId")
                        .HasColumnType("uuid")
                        .HasColumnName("bom_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.HasKey("BomId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("bom_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Delivery", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<Guid>("DeliveryPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_plan_id");

                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uuid")
                        .HasColumnName("franchise_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("DeliveryId");

                    b.HasIndex("DeliveryPlanId");

                    b.HasIndex("FranchiseId");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryItem", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.HasKey("DeliveryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("delivery_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryPlan", b =>
                {
                    b.Property<Guid>("DeliveryPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_plan_id");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("DeliveryPlanId");

                    b.ToTable("delivery_plans", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DemandAggregation", b =>
                {
                    b.Property<Guid>("DemandAggregationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("demand_aggregation_id");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at");

                    b.HasKey("DemandAggregationId");

                    b.ToTable("demand_aggregations", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DemandItem", b =>
                {
                    b.Property<Guid>("DemandAggregationId")
                        .HasColumnType("uuid")
                        .HasColumnName("demand_aggregation_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("total_quantity");

                    b.HasKey("DemandAggregationId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("demand_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Franchise", b =>
                {
                    b.Property<Guid>("FranchiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("franchise_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("FranchiseId");

                    b.ToTable("franchises", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("IngredientId");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.IngredientBatch", b =>
                {
                    b.Property<Guid>("IngredientBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_batch_id");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("batch_code");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uuid")
                        .HasColumnName("franchise_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.HasKey("IngredientBatchId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ingredient_batches", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.InventoryMovement", b =>
                {
                    b.Property<Guid>("InventoryMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_movement_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IngredientBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_batch_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("InventoryMovementId");

                    b.HasIndex("IngredientBatchId");

                    b.ToTable("inventory_movements", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("ProductId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", b =>
                {
                    b.Property<Guid>("ProductionPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("production_plan_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("KitchenFranchiseId")
                        .HasColumnType("uuid")
                        .HasColumnName("kitchen_franchise_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("ProductionPlanId");

                    b.HasIndex("KitchenFranchiseId");

                    b.ToTable("production_plans", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlanItem", b =>
                {
                    b.Property<Guid>("ProductionPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_plan_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.HasKey("ProductionPlanId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("production_plan_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ReceivingReport", b =>
                {
                    b.Property<Guid>("ReceivingReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("receiving_report_id");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.HasKey("ReceivingReportId");

                    b.HasIndex("DeliveryId");

                    b.ToTable("receiving_reports", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Recipe", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("RecipeId");

                    b.HasIndex("ProductId");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SalesRecord", b =>
                {
                    b.Property<Guid>("SalesRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sales_record_id");

                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uuid")
                        .HasColumnName("franchise_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("SoldAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sold_at");

                    b.HasKey("SalesRecordId");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("ProductId");

                    b.ToTable("sales_records", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreCatalog", b =>
                {
                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uuid")
                        .HasColumnName("franchise_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("FranchiseId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("store_catalog", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", b =>
                {
                    b.Property<Guid>("StoreOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("store_order_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uuid")
                        .HasColumnName("franchise_id");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("StoreOrderId");

                    b.HasIndex("FranchiseId");

                    b.ToTable("store_orders", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrderItem", b =>
                {
                    b.Property<Guid>("StoreOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.HasKey("StoreOrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("store_order_items", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Supplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_info");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("SupplierId");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SupportRequest", b =>
                {
                    b.Property<Guid>("SupportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("support_request_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SupportRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("support_requests", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.UserFranchise", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uuid")
                        .HasColumnName("franchise_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("UserId", "FranchiseId");

                    b.HasIndex("FranchiseId");

                    b.ToTable("user_franchises", (string)null);
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Allocation", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.DemandAggregation", "Aggregation")
                        .WithMany()
                        .HasForeignKey("DemandAggregationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aggregation");

                    b.Navigation("Approver");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.AllocationItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Allocation", "Allocation")
                        .WithMany("Items")
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allocation");

                    b.Navigation("Franchise");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.AuditLog", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Bom", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.BomItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Bom", "Bom")
                        .WithMany("Items")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bom");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Delivery", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.DeliveryPlan", "DeliveryPlan")
                        .WithMany()
                        .HasForeignKey("DeliveryPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryPlan");

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DeliveryItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Delivery", "Delivery")
                        .WithMany("Items")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DemandItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.DemandAggregation", "Aggregation")
                        .WithMany("Items")
                        .HasForeignKey("DemandAggregationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aggregation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.IngredientBatch", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.InventoryMovement", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.IngredientBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("IngredientBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Kitchen")
                        .WithMany()
                        .HasForeignKey("KitchenFranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitchen");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlanItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", "ProductionPlan")
                        .WithMany("Items")
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ReceivingReport", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Recipe", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SalesRecord", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreCatalog", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrderItem", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", "StoreOrder")
                        .WithMany("Items")
                        .HasForeignKey("StoreOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StoreOrder");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.SupportRequest", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.UserFranchise", b =>
                {
                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.Franchise", null)
                        .WithMany("UserFranchises")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralKitchenAndFranchise.DAL.Entities.User", null)
                        .WithMany("UserFranchises")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Allocation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Bom", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Delivery", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.DemandAggregation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.Franchise", b =>
                {
                    b.Navigation("UserFranchises");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.ProductionPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.StoreOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CentralKitchenAndFranchise.DAL.Entities.User", b =>
                {
                    b.Navigation("UserFranchises");
                });
#pragma warning restore 612, 618
        }
    }
}
